export const ACTIONS = {
    ADD_TO_CART: "ADD_TO_CART",
    REMOVE_FROM_CART: "REMOVE_FROM_CART",
    UPDATE_QUANTITY: "UPDATE_QUANTITY",
    CLEAR_CART: "CLEAR_CART",
    SET_SEARCH_QUERY: "SET_SEARCH_QUERY",
    SET_CATEGORY: "SET_CATEGORY",
    SET_SORT: "SET_SORT",
    TOGGLE_CART: "TOGGLE_CART",
}